import { create } from 'storybook/internal/theming';

export default create({
  base: 'light',
  brandTitle: 'Easemind | Storybook',
  brandImage: 'images/logo.png',
  brandTarget: '_self',
  colorPrimary: '#52cc68',
  colorSecondary: '#4b9c4f',
  appBg: '#ffffff',
  appContentBg: '#ffffff',
  appPreviewBg: '#ffffff',
  appBorderColor: '#9fc2a5',
  appBorderRadius: 4,
  textColor: '#10162F',
  textInverseColor: '#ffffff',
  barTextColor: '#9E9E9E',
  barSelectedColor: '#4b9c4f',
  barHoverColor: '#4b9c4f',
  barBg: '#ffffff',
  inputBg: '#ffffff',
  inputBorder: '#10162F',
  inputTextColor: '#10162F',
  inputBorderRadius: 2,
});